name: timelapsed-hrpqct
channels:
  - numerics88
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyyaml
  - scikit-image
  - scipy
  - simpleitk
  - pytest
  - pip
  - pip:
      - aimio-py
      - itk-elastix
      - -e .
