{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}
{% set project = pyproject["project"] %}
{% set version = project["version"] %}

package:
  name: timelapsed-hrpqct
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-build-isolation -vv"
  entry_points:
    - timelapse = timelapsedhrpqct.cli:main

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=3.11
    - numpy
    - pandas
    - pyyaml
    - scikit-image
    - scipy
    - simpleitk
    - pip

test:
  imports:
    - timelapsedhrpqct
  commands:
    - timelapse --help

about:
  home: https://github.com/matthiaswalle/TimelapsedHRpQCT
  summary: {{ project["description"] }}
  license: MIT

extra:
  recipe-maintainers:
    - matthiaswalle
